Ros1 devel
husarion/ros_components_description pull request #1
Opened 2022-10-10 11:03 UTC by pkowalsk1

2022-10-18 00:32 UTC, Kotochleb requested changes

2022-10-18 00:32 UTC, Kotochleb commented on package.xml
> +  <exec_depend>xacro</exec_depend>
```suggestion
  <depend>gazebo_ros</depend>
  <depend>urdf</depend>
  <depend>xacro</depend>
```

2022-10-18 00:32 UTC, Kotochleb commented on package.xml
> +<package format="2">
```suggestion
<package format="3">
```

2022-10-18 00:32 UTC, Kotochleb commented on package.xml
> +  <maintainer email="krzysztof.wojciechowski@husarion.com">Krzysztof Wojciechowski</maintainer>
```suggestion
  <maintainer email="krzysztof.wojciechowski@husarion.com">Krzysztof Wojciechowski</maintainer>
  <maintainer email="pawel.kowalski@husarion.com">Pawel Kowalski</maintainer>
```

2022-10-18 00:32 UTC, Kotochleb commented on urdf/orbbec_astra.gazebo.xacro
> +  <xacro:macro name="orbbec_astra" params="xyz rpy prefix:=front">
Parameters should match those from ROS 2

2022-10-18 00:32 UTC, Kotochleb commented on urdf/ouster_os1_32.gazebo.xacro
> +  <xacro:macro name="ouster_os1_32" params="xyz rpy use_gpu:=false prefix:=front topic:=laser/scan">
Parameters should match those from ROS 2

2022-10-18 00:32 UTC, Kotochleb commented on urdf/rplidar_s1.gazebo.xacro
> +  <xacro:macro name="rplidar_s1" params="xyz rpy use_gpu:=false prefix:=front topic:=laser/scan">
Parameters should match those from ROS 2

2022-10-18 00:32 UTC, Kotochleb commented on urdf/velodyne_puck.gazebo.xacro
> +  <xacro:macro name="velodyne_puck" params="xyz rpy use_gpu:=false prefix:=front topic:=laser/scan">
Parameters should match those from ROS 2

2022-10-20 12:51 UTC, pkowalsk1 commented on urdf/velodyne_puck.gazebo.xacro
> +              <samples>3600</samples>
In my case, this is the maximum value. More samples cause an error: 'Spawn service failed. Exiting.'

2022-10-20 13:11 UTC, pkowalsk1 commented on urdf/orbbec_astra.gazebo.xacro
> +    <link name="${tf_prefix_ext}orbbec_astra_link">
This frames orientation change was needed becouse depth image was rotated.

2022-10-21 08:25 UTC, KmakD requested changes

2022-10-21 08:25 UTC, KmakD commented on package.xml
> +  <maintainer email="pawel.kowalski@husarion.com">Pawel Kowalski</maintainer>
```suggestion
  <author email="krzysztof.wojciechowski@husarion.com">Krzysztof Wojciechowski</author>
  <author email="pawel.kowalski@husarion.com">Pawel Kowalski</author>
  <maintainer email="support@husarion.com">Husarion</maintainer>
```
I would mark people as authors

2022-10-21 08:25 UTC, KmakD commented on package.xml
> +  <exec_depend>xacro</exec_depend>
```suggestion
  <depend>gazebo_ros</depend>
  <depend>urdf</depend>
  <depend>xacro</depend>
```

2022-10-21 08:25 UTC, KmakD commented on urdf/orbbec_astra.gazebo.xacro
> +          <inertia ixx="1" ixy="0" ixz="0" iyy="1" iyz="0" izz="1" />
```suggestion
          <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
```

2022-10-21 08:25 UTC, KmakD commented on urdf/orbbec_astra.gazebo.xacro
> +    <link name="${tf_prefix_ext}${frame_id}"></link>
```suggestion
    <link name="${tf_prefix_ext}${frame_id}" />
```

2022-10-21 08:25 UTC, KmakD commented on urdf/ouster_os1_32.gazebo.xacro
> +          <mesh filename="file://$(find ros_components_description)/meshes/ouster_os1_32.stl" scale="1 1 0.65" />
```suggestion
          <mesh filename="file://$(find ros_components_description)/meshes/ouster_os1_32.stl" scale="1.0 1.0 0.65" />
```
Also, scale in z seems weird to me, is it intentional?

2022-10-21 08:25 UTC, KmakD commented on urdf/ouster_os1_32.gazebo.xacro
> +          <inertia ixx="1" ixy="0" ixz="0" iyy="1" iyz="0" izz="1" />
```suggestion
          <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
```

2022-10-21 08:25 UTC, KmakD commented on urdf/ouster_os1_32.gazebo.xacro
> +      <origin xyz="0 0 0.023" rpy="0 0 0" />
```suggestion
      <origin xyz="0.0 0.0 0.023" rpy="0.0 0.0 0.0" />
```

2022-10-21 08:25 UTC, KmakD commented on urdf/ouster_os1_32.gazebo.xacro
> +    <link name="${tf_prefix_ext}${frame_id}"></link>
```suggestion
    <link name="${tf_prefix_ext}${frame_id}" />
```

2022-10-21 08:25 UTC, KmakD commented on urdf/rplidar_s1.gazebo.xacro
> +        <origin xyz="0.0 0.0 ${0.051/2.0}" rpy="0 0 -${pi/2.0}"/>
```suggestion
        <origin xyz="0.0 0.0 ${0.051/2.0}" rpy="0.0 0.0 -${pi/2.0}"/>
```

2022-10-21 08:25 UTC, KmakD commented on urdf/rplidar_s1.gazebo.xacro
> +        <inertia ixx="1" ixy="0" ixz="0" iyy="1" iyz="0" izz="1" />
```suggestion
        <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
```

2022-10-21 08:25 UTC, KmakD commented on urdf/rplidar_s1.gazebo.xacro
> +    <link name="${tf_prefix_ext}${frame_id}"></link>
```suggestion
    <link name="${tf_prefix_ext}${frame_id}" />
```

2022-10-21 08:25 UTC, KmakD commented on urdf/velodyne_puck.gazebo.xacro
> +        <inertia ixx="1" ixy="0" ixz="0" iyy="1" iyz="0" izz="1" />
```suggestion
        <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
```

2022-10-24 08:15 UTC, KmakD requested changes

2022-10-24 08:15 UTC, KmakD commented on urdf/ouster_os1_32.gazebo.xacro
> +          <mesh filename="file://$(find ros_components_description)/meshes/ouster_os1_32.stl" scale="1.0 1.0 0.65" />
```suggestion
          <mesh filename="file://$(find ros_components_description)/meshes/ouster_os1_32.stl" scale="1.0 1.0 1.0" />
```
scale in z seems a bit weird

2022-10-24 09:11 UTC, KmakD approved these changes

2022-10-24 12:33 UTC, merged