Added requested receiver tf to wireless charging station
husarion/ros_components_description pull request #55
Opened 2024-10-29 13:25 UTC by delihus

2024-10-30 16:27 UTC, rafal-gorecki requested changes
In simulation station is upside down
![image](https://github.com/user-attachments/assets/e90bfcb9-0069-4c5f-ba8a-687c8e622496)

2024-10-31 15:15 UTC, delihus commented
I added background for an apriltag.

I forgot to change docking components for  these changes for simulation:
https://github.com/husarion/panther_ros/pull/431/commits/d4edaaf86f61572a969feb20a6fa3c6123f7b4c0

2024-11-05 16:34 UTC, rafal-gorecki commented
It is correct?
![image](https://github.com/user-attachments/assets/37899d25-472e-46c4-a94d-be0813d7d62a)

2024-11-08 08:36 UTC, rafal-gorecki approved these changes

2024-11-08 08:37 UTC, merged